name: CI Linux
on:
  workflow_dispatch:

jobs:
  build-binaries-unix:
    name: Build unix lib
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    steps:
      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Checkout libplacebo Repository
        uses: actions/checkout@v2
        with:
          repository: haasn/libplacebo
          path: libplacebo
          ref: v6.338.1
          submodules: recursive

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y libavcodec-dev libavformat-dev libegl1-mesa-dev libsdl2-dev libxxhash-dev glslang-dev libvulkan-dev liblcms2-dev

      - name: Install Meson and Ninja
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip3 install --upgrade meson==1.3.0
          pip3 install --upgrade ninja==1.11.1

      - name: Build libplacebo
        working-directory: ./libplacebo
        run: |
          meson setup build --buildtype release --default-library=static -Ddemos=false -Dprefix=$PWD/install
          meson compile -vC build
          meson install -C build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-library-artifacts
          path: libplacebo/install
