name: CI macOS

on:
  workflow_dispatch:

jobs:
  build-binaries-macos:
    name: Build macOS lib
    strategy:
      matrix:
        arch: [x86_64, arm64]

    runs-on: ${{ matrix.arch == 'x86_64' && 'macos-14-large' || 'macos-14' }}

    steps:
      - name: Checkout libplacebo Repository
        uses: actions/checkout@v2
        with:
          repository: haasn/libplacebo
          path: libplacebo
          ref: v6.338.1
          submodules: recursive

      - name: Download and Install Vulkan SDK Manually using DMG
        run: |
          # Download the LunarG Vulkan SDK DMG
          VULKAN_VERSION="1.3.280.1"
          curl -LO https://sdk.lunarg.com/sdk/download/${VULKAN_VERSION}/mac/vulkansdk-macos-${VULKAN_VERSION}.dmg
          
          # Mount the DMG file
          MOUNT_PATH=$(hdiutil mount vulkansdk-macos-${VULKAN_VERSION}.dmg | tail -n1 | awk '{print $3}')
          
          # Install Vulkan SDK from DMG
          sudo "${MOUNT_PATH}/InstallVulkan.app/Contents/MacOS/InstallVulkan" \
            --root ~/VulkanSDK/${VULKAN_VERSION} \
            --accept-licenses --default-answer --confirm-command \
            install com.lunarg.vulkan.core com.lunarg.vulkan.usr com.lunarg.vulkan.sdl2 com.lunarg.vulkan.glm com.lunarg.vulkan.volk com.lunarg.vulkan.vma
          
          # Unmount the DMG after installation
          hdiutil unmount "${MOUNT_PATH}"

      - name: Set environment variables for Vulkan SDK
        run: |
          # Set environment variables for Vulkan SDK
          export VULKAN_SDK=~/VulkanSDK/1.3.280.1
          export PATH="$VULKAN_SDK/bin:$PATH"
          export CFLAGS="-arch ${{ matrix.arch }} -I$VULKAN_SDK/include -I$(brew --prefix vulkan-headers)/include"
          export LDFLAGS="-arch ${{ matrix.arch }} -L$VULKAN_SDK/lib -L$(brew --prefix vulkan-loader)/lib"
          export PKG_CONFIG_PATH="$VULKAN_SDK/lib/pkgconfig:$(brew --prefix vulkan-loader)/lib/pkgconfig:$PKG_CONFIG_PATH"
          export CC="clang"
          export CXX="clang++"
          echo "Environment variables set: VULKAN_SDK=$VULKAN_SDK, CFLAGS=$CFLAGS, LDFLAGS=$LDFLAGS, PKG_CONFIG_PATH=$PKG_CONFIG_PATH"

      - name: Install dependencies with Homebrew
        run: |
          brew update
          brew install pkg-config meson ninja jq \
                       lcms2 sdl2

      - name: Build libplacebo
        working-directory: ./libplacebo
        run: |
          meson setup build --buildtype release --default-library=static -Ddemos=false -Dprefix=$PWD/install
          meson compile -vC build
          meson install -C build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-library-artifacts-${{ matrix.arch }}
          path: libplacebo/install
